[versions]
agp = "9.4.1"
kotlin = "2.4.20" # https://kotlinlang.org/docs/releases.html

[libraries]
voir-decimal = { module = "dev.voir:decimal", version = "1.0.3" }

[plugins]
androidMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
